#this file holds constants relevant to every file

HOST = "localhost"
MARKET_PORT = 22026
MAIN_PORT = 22027
SHARED_MEMORY_KEY = b'Dinosour'
SHARED_MEMORY_PORT = 22028
MESSAGE_QUEUE_KEY = 64
STD_TEMP = 15
STD_ENERGY = 3
STD_PRICE = 0.15
INIT_BALANCE = 10
INIT_ENERGY = 5